### ISSUE TITLE
[Bug] when autocraftign with Xnet, Modifiers/ FE input blocks do not make correct versions

### ISSUE THREAD

**Issue by Pdiddy973** [ValkyrieofNight/EnvironmentalTech#234]
when trying to automate the assemblers with x net, i have all the correct item go in and it crafts, how ever it does not make the proper item until i place/break it, and makes automating the higher tier modifiers/FE inputs impossible

After auto crafting:
![image](https://user-images.githubusercontent.com/68764896/103147343-51b1d080-4722-11eb-9be3-2e4502977102.png)

After Break/Replace:
![image](https://user-images.githubusercontent.com/68764896/103147384-6c844500-4722-11eb-9cc9-b42ae03f225e.png)

Envirocore: 3.0.5.3
Envirotech: 5.0.5.1

**Comment by ValkyrieofNight** [comment]
This should be fixed in latest version

**Comment by Pdiddy973** [comment]
this is still not working on version 3.0.6.1 for ET and 3.0.6.0 for EC, now placing/breaking wont fix.these are the following step i need to do to auto craft it, not sure if its intended 
![image](https://user-images.githubusercontent.com/68764896/104134617-d292de00-5358-11eb-829d-cf230362164e.png)
![image](https://user-images.githubusercontent.com/68764896/104134625-daeb1900-5358-11eb-9278-310aa3f147af.png)
then to upgrade to what ever teir:
![image](https://user-images.githubusercontent.com/68764896/104134627-e8a09e80-5358-11eb-8948-638faa7dbd34.png)

**Comment by Pdiddy973** [comment]
the FE input block still does not work at all, when auto crafted it gives the FE input item but has incorrect NBT data it seems, even after upgrading 
![image](https://user-images.githubusercontent.com/68764896/104134943-d889be80-535a-11eb-85ac-4b8e7119b973.png)
