### ISSUE TITLE
Cannot break void miner

### ISSUE THREAD

**Issue by weedenbc** [ValkyrieofNight/EnvironmentalTech#85]
I'm playing a game using the new direwolf20 pack, and have 3 tier 1 void ore miners created. They all work, but I can't break any blocks on the first two. I wanted to do so in order to change out the lens filter,  but it seems nothing I do will work. I tried mining them with every pick I have (normal, tinkers, AA drill). I get a  block break sound and the particle effects, but it's like it instantly pops back into place. And the miner keeps working. I even tried popping into creative mode, and the same thing happened. 

I just built a third tier 1 miner, and that one I can break blocks on normally.

**Comment by ValkyrieofNight** [comment]
Yeah this is a bug. It's because the owner system was just introduced to the multiblocks amd existing multiblocks don't have owners. Fix is coming very soon.

**Comment by futurerealm** [comment]
Good to know you are aware of this issue. I just encountered the same problem. My first ore miner was working fine all day and it just started that random unbreakable problem recently. I created an account specifically to comment on this because it's a big issue. When you say fix soon, what do you consider soon? Within a week? A month? Not sure how frequent updates are.

**Comment by ValkyrieofNight** [comment]
Had a lot on recently but it should be out within next few days. Should be out by Friday

**Comment by futurerealm** [comment]
Thanks so much for the hard work!

**Comment by MoonStalk** [comment]
updated DW20 1.12.2 to 1.4.0
then updated ET and library to 2.0.6

Problem still exists for all machines.

Do I need to switch back to 2.0.4, break down all the machines, upgrade them rebuild them?
is there a command that can be run to "assign" a machine to a user?

**Comment by ValkyrieofNight** [comment]
Right click the controller

**Comment by MoonStalk** [comment]
Doesn't show ownership when clicking the controller for the solar array, but it does the trick.

Thanks

**Comment by TonyTheTigerTTT** [comment]
I have the same problem, Also updated to DW20 1.4 i hopes that this would solve it, it has not.
It says nothing when i rightclick the controller with a hand, with the assembler it says "multiblock complete" but i still cant break it, not even in creative. please help asap :)

**Comment by MoonStalk** [comment]
DW20 1.4 does not have v2.0.6 included.  You need to manually update ET and the library to 2.0.6

**Comment by weedenbc** [comment]
Manually updated v2.0.6 (don't forget the valkyrielib as well!) and the bug is fixed. Thanks.

**Comment by jsuelwald** [comment]
Problem still exists with current mod-versions within the ftb-relevations-modpack

(version 2.0.7b)

**Comment by sdreamer2000** [comment]
Problem still exists with Direwolf 20 pack.  Updated to version 9b, (tried 9c and game didn't seem to recognize)  Please advise.

**Comment by nevillution** [comment]
I can confirm the issue affects **environmentaltech-1.12.2-2.0.8a.jar** in DW20 1.12

**Comment by brandonleon** [comment]
Also affecting 2.0.8b, cant even remove it in creative mode.

**Comment by nevillution** [comment]
I was able to work-around by sneak-rightclick with the wrench from Environmental Tech. This will allow for breaking of any block and allowed me to actually destroy and upgrade the tier 2 Void Miner.

**Comment by sdreamer2000** [comment]
Thank you so much!  Sorry it took so long for me to get back, but it worked!  I appreciate the help!
Thanks again,sdreamer2000
    On Monday, May 21, 2018, 5:39:42 PM EDT, nevillution <notifications@github.com> wrote:  
 
 
I was able to work-around by sneak-rightclick with the wrench from Environmental Tech. This will allow for breaking of any block and allowed me to actually destroy and upgrade the tier 2 Void Miner.

**Comment by nevillution** [comment]
Anyone still having an issue, definitely try holding **shift** and right-click with the Assembler ![assembler](https://user-images.githubusercontent.com/30152896/41361350-daf87b1a-6efc-11e8-91d1-92e68dc79de4.png)
